const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, 'data', 'words.json');

// 50 Verbs
const verbs = [
  { word: "accept", meaning: "kabul etmek", sentenceEn: "She decided to accept the new job offer.", sentenceTr: "Yeni iş teklifini kabul etmeye karar verdi." },
  { word: "achieve", meaning: "başarmak, elde etmek", sentenceEn: "They worked hard to achieve their annual goals.", sentenceTr: "Yıllık hedeflerini başarmak için çok çalıştılar." },
  { word: "admit", meaning: "itiraf etmek, kabul etmek", sentenceEn: "He had to admit that he made a mistake.", sentenceTr: "Bir hata yaptığını itiraf etmek zorunda kaldı." },
  { word: "agree", meaning: "aynı fikirde olmak, anlaşmak", sentenceEn: "I completely agree with your suggestion.", sentenceTr: "Önerine kesinlikle katılıyorum." },
  { word: "allow", meaning: "izin vermek", sentenceEn: "The hotel does not allow pets inside.", sentenceTr: "Otel içeriye evcil hayvan girmesine izin vermiyor." },
  { word: "appear", meaning: "görünmek, belirmek", sentenceEn: "A strange light began to appear in the sky.", sentenceTr: "Gökyüzünde garip bir ışık belirmeye başladı." },
  { word: "apply", meaning: "başvurmak, uygulamak", sentenceEn: "You should apply for this scholarship immediately.", sentenceTr: "Bu bursa hemen başvurmalısın." },
  { word: "arrive", meaning: "varmak, ulaşmak", sentenceEn: "The train will arrive in ten minutes.", sentenceTr: "Tren on dakika içinde varacak." },
  { word: "avoid", meaning: "kaçınmak, uzak durmak", sentenceEn: "Try to avoid eating junk food before bed.", sentenceTr: "Yatmadan önce abur cubur yemekten kaçınmaya çalışın." },
  { word: "believe", meaning: "inanmak", sentenceEn: "I strongly believe that practice brings success.", sentenceTr: "Pratik yapmanın başarı getirdiğine güçlü bir şekilde inanıyorum." },
  { word: "borrow", meaning: "ödünç almak", sentenceEn: "Can I borrow your English dictionary for today?", sentenceTr: "Bugünlük İngilizce sözlüğünü ödünç alabilir miyim?" },
  { word: "cancel", meaning: "iptal etmek", sentenceEn: "They had to cancel the meeting due to heavy rain.", sentenceTr: "Şiddetli yağmur nedeniyle toplantıyı iptal etmek zorunda kaldılar." },
  { word: "choose", meaning: "seçmek", sentenceEn: "You can choose whatever topic you like.", sentenceTr: "İstediğin herhangi bir konuyu seçebilirsin." },
  { word: "complain", meaning: "şikayet etmek", sentenceEn: "Customers often complain about long delivery times.", sentenceTr: "Müşteriler sık sık uzun teslimat sürelerinden şikayet eder." },
  { word: "confirm", meaning: "onaylamak, teyit etmek", sentenceEn: "Please click the link to confirm your reservation.", sentenceTr: "Rezervasyonunuzu onaylamak için lütfen bağlantıya tıklayın." },
  { word: "consider", meaning: "göz önünde bulundurmak, düşünmek", sentenceEn: "You should consider all options before deciding.", sentenceTr: "Karar vermeden önce tüm seçenekleri göz önünde bulundurmalısın." },
  { word: "create", meaning: "oluşturmak, yaratmak", sentenceEn: "This program will help you create modern websites.", sentenceTr: "Bu program modern web siteleri oluşturmanıza yardımcı olacak." },
  { word: "decide", meaning: "karar vermek", sentenceEn: "It is hard to decide which path to take.", sentenceTr: "Hangi yolu seçeceğine karar vermek zordur." },
  { word: "describe", meaning: "tarif etmek, tanımlamak", sentenceEn: "Can you describe the person you saw yesterday?", sentenceTr: "Dün gördüğün kişiyi tarif edebilir misin?" },
  { word: "destroy", meaning: "yıkmak, yok etmek", sentenceEn: "The earthquake destroyed several old buildings.", sentenceTr: "Deprem birkaç eski binayı yıktı." },
  { word: "develop", meaning: "geliştirmek, gelişmek", sentenceEn: "Reading every day will develop your vocabulary.", sentenceTr: "Her gün okumak kelime dağarcığınızı geliştirecektir." },
  { word: "discover", meaning: "keşfetmek", sentenceEn: "Scientists discover new species every single year.", sentenceTr: "Bilim insanları her yıl yeni türler keşfeder." },
  { word: "discuss", meaning: "tartışmak, görüşmek", sentenceEn: "We need to discuss the project budget tomorrow.", sentenceTr: "Yarın proje bütçesini görüşmemiz gerekiyor." },
  { word: "encourage", meaning: "cesaretlendirmek, teşvik etmek", sentenceEn: "Teachers should encourage students to speak English.", sentenceTr: "Öğretmenler öğrencileri İngilizce konuşmaya teşvik etmelidir." },
  { word: "explain", meaning: "açıklamak, izah etmek", sentenceEn: "Could you explain the grammar rule once again?", sentenceTr: "Dilbilgisi kuralını bir kez daha açıklayabilir misiniz?" },
  { word: "focus", meaning: "odaklanmak", sentenceEn: "Turn off your phone to focus on your studies.", sentenceTr: "Derslerinize odaklanmak için telefonunuzu kapatın." },
  { word: "forgive", meaning: "affetmek, bağışlamak", sentenceEn: "It is not always easy to forgive people.", sentenceTr: "İnsanları affetmek her zaman kolay değildir." },
  { word: "happen", meaning: "meydana gelmek, olmak", sentenceEn: "Unexpected things can happen at any moment.", sentenceTr: "Her an beklenmedik şeyler meydana gelebilir." },
  { word: "improve", meaning: "geliştirmek, iyileştirmek", sentenceEn: "Daily practice will improve your speaking skills.", sentenceTr: "Günlük pratik konuşma becerilerinizi geliştirecektir." },
  { word: "increase", meaning: "artırmak, artmak", sentenceEn: "The company plans to increase production next month.", sentenceTr: "Şirket gelecek ay üretimi artırmayı planlıyor." },
  { word: "inform", meaning: "bilgilendirmek, haber vermek", sentenceEn: "Please inform us if your plans change.", sentenceTr: "Planlarınız değişirse lütfen bizi bilgilendirin." },
  { word: "inspire", meaning: "ilham vermek", sentenceEn: "Her success story will inspire many young people.", sentenceTr: "Onun başarı hikayesi birçok gence ilham verecektir." },
  { word: "introduce", meaning: "tanıtmak, tanıştırmak", sentenceEn: "Allow me to introduce my colleague, David.", sentenceTr: "Meslektaşım David'i tanıtmama izin verin." },
  { word: "invite", meaning: "davet etmek", sentenceEn: "They decided to invite all their neighbors to dinner.", sentenceTr: "Tüm komşularını akşam yemeğine davet etmeye karar verdiler." },
  { word: "manage", meaning: "yönetmek, başarmak", sentenceEn: "He managed to finish the report on time.", sentenceTr: "Raporu zamanında bitirmeyi başardı." },
  { word: "notice", meaning: "fark etmek", sentenceEn: "Did you notice the mistake in the first paragraph?", sentenceTr: "İlk paragraftaki hatayı fark ettin mi?" },
  { word: "offer", meaning: "teklif etmek, sunmak", sentenceEn: "They offered him a great salary for the position.", sentenceTr: "Pozisyon için ona harika bir maaş teklif ettiler." },
  { word: "prefer", meaning: "tercih etmek", sentenceEn: "I prefer tea over coffee in the morning.", sentenceTr: "Sabahları çayı kahveye tercih ederim." },
  { word: "prepare", meaning: "hazırlamak, hazırlanmak", sentenceEn: "She spent two hours preparing for the interview.", sentenceTr: "Mülakata hazırlanmak için iki saat harcadı." },
  { word: "prevent", meaning: "önlemek, engel olmak", sentenceEn: "Wearing a helmet can prevent serious injuries.", sentenceTr: "Kask takmak ciddi yaralanmaları önleyebilir." },
  { word: "promise", meaning: "söz vermek", sentenceEn: "I promise to return the book by Friday.", sentenceTr: "Kitabı cumaya kadar geri getireceğime söz veriyorum." },
  { word: "protect", meaning: "korumak", sentenceEn: "Good passwords protect your account from hackers.", sentenceTr: "Güçlü parolalar hesabınızı korsanlardan korur." },
  { word: "receive", meaning: "teslim almak, kabul etmek", sentenceEn: "Did you receive my email about the meeting?", sentenceTr: "Toplantıyla ilgili e-postamı teslim aldın mı?" },
  { word: "recommend", meaning: "tavsiye etmek, önermek", sentenceEn: "Which restaurant would you recommend in this city?", sentenceTr: "Bu şehirde hangi restoranı tavsiye edersiniz?" },
  { word: "refuse", meaning: "reddetmek, geri çevirmek", sentenceEn: "He refused to sign the contract without reading.", sentenceTr: "Okumadan sözleşmeyi imzalamayı reddetti." },
  { word: "remember", meaning: "hatırlamak", sentenceEn: "Always remember to save your work before closing.", sentenceTr: "Kapatmadan önce çalışmanızı kaydetmeyi daima hatırlayın." },
  { word: "require", meaning: "gerektirmek, istemek", sentenceEn: "This job requires fluent English and communication skills.", sentenceTr: "Bu iş akıcı İngilizce ve iletişim becerileri gerektirir." },
  { word: "suggest", meaning: "önermek, tavsiye etmek", sentenceEn: "The doctor suggested taking a short walk every day.", sentenceTr: "Doktor her gün kısa bir yürüyüş yapmayı önerdi." },
  { word: "support", meaning: "desteklemek", sentenceEn: "My family always supports my career choices.", sentenceTr: "Ailem kariyer seçimlerimi her zaman destekler." },
  { word: "understand", meaning: "anlamak", sentenceEn: "Listen carefully so you can understand the instructions.", sentenceTr: "Talimatları anlayabilmek için dikkatlice dinleyin." }
];

// 50 Adjectives
const adjectives = [
  { word: "accurate", meaning: "doğru, kesin, hatasız", sentenceEn: "We need accurate data to complete the report.", sentenceTr: "Raporu tamamlamak için doğru verilere ihtiyacımız var." },
  { word: "adequate", meaning: "yeterli, kafi", sentenceEn: "The room has adequate space for four people.", sentenceTr: "Oda dört kişi için yeterli alana sahip." },
  { word: "ancient", meaning: "antik, çok eski", sentenceEn: "They visited an ancient temple in Greece.", sentenceTr: "Yunanistan'da antik bir tapınağı ziyaret ettiler." },
  { word: "anxious", meaning: "endişeli, kaygılı", sentenceEn: "She felt anxious before the exam started.", sentenceTr: "Sınav başlamadan önce endişeli hissetti." },
  { word: "appropriate", meaning: "uygun, münasip", sentenceEn: "Wear appropriate clothes for the job interview.", sentenceTr: "İş görüşmesi için uygun kıyafetler giyin." },
  { word: "aware", meaning: "farkında, haberdar", sentenceEn: "Are you aware of the new company policy?", sentenceTr: "Yeni şirket politikasının farkında mısınız?" },
  { word: "brave", meaning: "cesur, yürekli", sentenceEn: "The brave firefighter saved the little cat.", sentenceTr: "Cesur itfaiyeci küçük kediyi kurtardı." },
  { word: "brief", meaning: "kısa, öz", sentenceEn: "He gave a brief summary of the project.", sentenceTr: "Projenin kısa ve öz bir özetini sundu." },
  { word: "calm", meaning: "sakin, dingin", sentenceEn: "Try to stay calm during an emergency.", sentenceTr: "Acil bir durumda sakin kalmaya çalışın." },
  { word: "cautious", meaning: "temkinli, tedbirli", sentenceEn: "Drivers must be cautious on icy roads.", sentenceTr: "Sürücüler buzlu yollarda temkinli olmalıdır." },
  { word: "confident", meaning: "kendine güvenen, emin", sentenceEn: "She gave a confident presentation to the board.", sentenceTr: "Yönetim kuruluna kendine güvenen bir sunum yaptı." },
  { word: "convenient", meaning: "elverişli, uygun, pratik", sentenceEn: "Online shopping is very convenient for busy people.", sentenceTr: "İnternetten alışveriş meşgul insanlar için çok elverişlidir." },
  { word: "creative", meaning: "yaratıcı, üretken", sentenceEn: "We need creative solutions to solve this problem.", sentenceTr: "Bu sorunu çözmek için yaratıcı çözümlere ihtiyacımız var." },
  { word: "crucial", meaning: "çok önemli, hayati", sentenceEn: "Good sleep is crucial for overall health.", sentenceTr: "İyi bir uyku genel sağlık için hayati önem taşır." },
  { word: "curious", meaning: "meraklı", sentenceEn: "Children are naturally curious about the world.", sentenceTr: "Çocuklar doğal olarak dünya hakkında meraklıdırlar." },
  { word: "delightful", meaning: "hoş, zevkli, sevindirici", sentenceEn: "We had a delightful dinner with our friends.", sentenceTr: "Arkadaşlarımızla çok hoş bir akşam yemeği yedik." },
  { word: "determined", meaning: "kararlı, azimli", sentenceEn: "He is determined to learn English this year.", sentenceTr: "Bu yıl İngilizce öğrenmeye kararlı." },
  { word: "efficient", meaning: "verimli, etkili", sentenceEn: "This new machine is fast and efficient.", sentenceTr: "Bu yeni makine hızlı ve verimlidir." },
  { word: "embarrassed", meaning: "utanmış, mahcup", sentenceEn: "He felt embarrassed when he dropped his tray.", sentenceTr: "Tepsisini düşürdüğünde mahcup hissetti." },
  { word: "enthusiastic", meaning: "hevesli, coşkulu", sentenceEn: "The team was enthusiastic about the new project.", sentenceTr: "Ekip yeni proje konusunda oldukça hevesliydi." },
  { word: "essential", meaning: "temel, gerekli, vazgeçilmez", sentenceEn: "Water is essential for all living creatures.", sentenceTr: "Su tüm canlılar için vazgeçilmezdir." },
  { word: "familiar", meaning: "tanıdık, aşina", sentenceEn: "Her face looked familiar, but I forgot her name.", sentenceTr: "Yüzü tanıdık geliyordu ama adını unuttum." },
  { word: "fascinating", meaning: "büyüleyici, son derece ilginç", sentenceEn: "Space exploration is a fascinating topic.", sentenceTr: "Uzay araştırmaları büyüleyici bir konudur." },
  { word: "flexible", meaning: "esnek, uyum sağlayabilen", sentenceEn: "Remote workers enjoy having flexible hours.", sentenceTr: "Uzaktan çalışanlar esnek çalışma saatlerine sahip olmayı sever." },
  { word: "generous", meaning: "cömert, eli açık", sentenceEn: "The generous man donated money to the charity.", sentenceTr: "Cömert adam hayır kurumuna para bağışladı." },
  { word: "grateful", meaning: "minnettar, müteşekkir", sentenceEn: "I am grateful for all your support.", sentenceTr: "Tüm desteğiniz için minnettarım." },
  { word: "guilty", meaning: "suçlu, kabahatli", sentenceEn: "He felt guilty about missing his friend's party.", sentenceTr: "Arkadaşının partisini kaçırdığı için kendini suçlu hissetti." },
  { word: "harsh", meaning: "sert, acımasız, haşin", sentenceEn: "Winter in Canada can be very harsh.", sentenceTr: "Kanada'da kış mevsimi çok sert geçebilir." },
  { word: "hesitant", meaning: "tereddütlü, kararsız", sentenceEn: "She was hesitant to speak in front of the crowd.", sentenceTr: "Kalabalığın önünde konuşma konusunda tereddütlüydü." },
  { word: "huge", meaning: "kocaman, devasa", sentenceEn: "They bought a house with a huge garden.", sentenceTr: "Kocaman bir bahçesi olan bir ev satın aldılar." },
  { word: "innocent", meaning: "masum, suçsuz", sentenceEn: "The court decided that the young boy was innocent.", sentenceTr: "Mahkeme genç çocuğun masum olduğuna karar verdi." },
  { word: "jealous", meaning: "kıskanç", sentenceEn: "He was jealous of his brother's success.", sentenceTr: "Kardeşinin başarısını kıskanıyordu." },
  { word: "loyal", meaning: "sadık, vefalı", sentenceEn: "A dog is known as a loyal companion.", sentenceTr: "Köpek sadık bir yoldaş olarak bilinir." },
  { word: "massive", meaning: "devasa, çok büyük", sentenceEn: "A massive rock blocked the mountain road.", sentenceTr: "Devasa bir kaya dağ yolunu kapattı." },
  { word: "mature", meaning: "olgun, yetişkin", sentenceEn: "She showed very mature behavior during the crisis.", sentenceTr: "Kriz sırasında çok olgun bir davranış sergiledi." },
  { word: "mysterious", meaning: "gizemli, esrarengiz", sentenceEn: "They found a mysterious box in the attic.", sentenceTr: "Tavan arasında gizemli bir kutu buldular." },
  { word: "narrow", meaning: "dar, kısıtlı", sentenceEn: "The old town had very narrow streets.", sentenceTr: "Eski kasabanın çok dar sokakları vardı." },
  { word: "obvious", meaning: "aşikar, apaçık, belli", sentenceEn: "It is obvious that she loves painting.", sentenceTr: "Resim yapmayı sevdiği apaçık ortada." },
  { word: "patient", meaning: "sabırlı", sentenceEn: "Learning a language requires being patient.", sentenceTr: "Dil öğrenmek sabırlı olmayı gerektirir." },
  { word: "polite", meaning: "kibar, nazik", sentenceEn: "It is important to be polite to waiters.", sentenceTr: "Garsonlara karşı kibar olmak önemlidir." },
  { word: "precious", meaning: "değerli, kıymetli", sentenceEn: "Time is the most precious resource we have.", sentenceTr: "Zaman sahip olduğumuz en kıymetli kaynaktır." },
  { word: "reliable", meaning: "güvenilir, sağlam", sentenceEn: "He is a reliable friend who always keeps secrets.", sentenceTr: "O her zaman sır tutan güvenilir bir arkadaştır." },
  { word: "rough", meaning: "pürüzlü, kaba, dalgalı", sentenceEn: "The sea was too rough for swimming.", sentenceTr: "Deniz yüzmek için fazlasıyla dalgalıydı." },
  { word: "scarce", meaning: "kıt, nadir, yetersiz", sentenceEn: "Clean drinking water is scarce in some regions.", sentenceTr: "Bazı bölgelerde temiz içme suyu kıttır." },
  { word: "sensible", meaning: "mantıklı, aklı başında", sentenceEn: "Saving money every month is a sensible choice.", sentenceTr: "Her ay para biriktirmek mantıklı bir seçimdir." },
  { word: "strict", meaning: "katı, sert, disiplinli", sentenceEn: "The school has strict rules regarding attendance.", sentenceTr: "Okulun devamlılık konusunda katı kuralları vardır." },
  { word: "talented", meaning: "yetenekli, kabiliyetli", sentenceEn: "She is a very talented piano player.", sentenceTr: "O çok yetenekli bir piyano sanatçısıdır." },
  { word: "urgent", meaning: "acil, ivedi", sentenceEn: "I need to make an urgent phone call.", sentenceTr: "Acil bir telefon görüşmesi yapmam gerekiyor." },
  { word: "valuable", meaning: "değerli, yararlı", sentenceEn: "This book provides valuable advice for beginners.", sentenceTr: "Bu kitap yeni başlayanlar için değerli tavsiyeler sunuyor." },
  { word: "vivid", meaning: "canlı, parlak, berrak", sentenceEn: "I still have a vivid memory of that sunny day.", sentenceTr: "O güneşli güne dair hala çok canlı bir hatıram var." }
];

// 50 Nouns / Objects
const nouns = [
  { word: "bag", meaning: "çanta", sentenceEn: "She put her wallet inside the leather bag.", sentenceTr: "Cüzdanını deri çantanın içine koydu." },
  { word: "bottle", meaning: "şişe", sentenceEn: "Please fill the glass water bottle.", sentenceTr: "Lütfen cam su şişesini doldurun." },
  { word: "bridge", meaning: "köprü", sentenceEn: "They built a new bridge over the river.", sentenceTr: "Nehrin üzerine yeni bir köprü inşa ettiler." },
  { word: "calendar", meaning: "takvim", sentenceEn: "I marked the exam date on my calendar.", sentenceTr: "Sınav tarihini takvimime işaretledim." },
  { word: "camera", meaning: "kamera, fotoğraf makinesi", sentenceEn: "He took great photos with his new camera.", sentenceTr: "Yeni fotoğraf makinesiyle harika fotoğraflar çekti." },
  { word: "candle", meaning: "mum", sentenceEn: "She lit a scented candle in the living room.", sentenceTr: "Oturma odasında kokulu bir mum yaktı." },
  { word: "carpet", meaning: "halı", sentenceEn: "The warm carpet made the room feel cozy.", sentenceTr: "Sıcak halı odanın samimi hissettirmesini sağladı." },
  { word: "clock", meaning: "saat (duvar/masa)", sentenceEn: "The clock on the wall stopped ticking.", sentenceTr: "Duvardaki saat tıkırdamayı bıraktı." },
  { word: "coat", meaning: "kaban, palto", sentenceEn: "Put on your heavy coat because it is freezing.", sentenceTr: "Kalın kabanını giy çünkü hava buz gibi." },
  { word: "computer", meaning: "bilgisayar", sentenceEn: "He uses his computer to write software.", sentenceTr: "Yazılım yazmak için bilgisayarını kullanıyor." },
  { word: "cup", meaning: "fincan, kupa", sentenceEn: "I drank a hot cup of green tea.", sentenceTr: "Sıcak bir fincan yeşil çay içtim." },
  { word: "desk", meaning: "çalışma masası", sentenceEn: "Clean your desk before starting your work.", sentenceTr: "İşe başlamadan önce çalışma masanı temizle." },
  { word: "door", meaning: "kapı", sentenceEn: "Please lock the front door when you leave.", sentenceTr: "Ayrılırken lütfen ön kapıyı kilitleyin." },
  { word: "drawer", meaning: "çekmece", sentenceEn: "The passport is in the top drawer.", sentenceTr: "Pasaport en üstteki çekmecededir." },
  { word: "envelope", meaning: "zarf (mektup)", sentenceEn: "He sealed the letter inside the white envelope.", sentenceTr: "Mektubu beyaz zarfın içine mühürledi." },
  { word: "fork", meaning: "çatal", sentenceEn: "Use a fork and knife to eat your steak.", sentenceTr: "Bifteğinizi yemek için çatal ve bıçak kullanın." },
  { word: "glasses", meaning: "gözlük", sentenceEn: "I cannot read small letters without my glasses.", sentenceTr: "Gözlüğüm olmadan küçük harfleri okuyamıyorum." },
  { word: "hammer", meaning: "çekiç", sentenceEn: "He used a hammer to put a nail into the wall.", sentenceTr: "Duvara bir çivi çakmak için çekiç kullandı." },
  { word: "headphones", meaning: "kulaklık", sentenceEn: "Put on your headphones to listen to the podcast.", sentenceTr: "Podcasti dinlemek için kulaklığını tak." },
  { word: "key", meaning: "anahtar", sentenceEn: "I accidentally left my car key inside the house.", sentenceTr: "Araba anahtarımı kazara evin içinde unuttum." },
  { word: "knife", meaning: "bıçak", sentenceEn: "Be careful because this kitchen knife is very sharp.", sentenceTr: "Dikkatli ol çünkü bu mutfak bıçağı çok keskin." },
  { word: "ladder", meaning: "merdiven (taşınabilir)", sentenceEn: "He climbed the ladder to paint the ceiling.", sentenceTr: "Tavanı boyamak için merdivene tırmandı." },
  { word: "lamp", meaning: "lamba, abajur", sentenceEn: "Turn on the reading lamp on the nightstand.", sentenceTr: "Komodinin üzerindeki okuma lambasını aç." },
  { word: "mirror", meaning: "ayna", sentenceEn: "She looked in the mirror before heading out.", sentenceTr: "Dışarı çıkmadan önce aynaya baktı." },
  { word: "notebook", meaning: "not defteri", sentenceEn: "Write down new vocabulary in your notebook.", sentenceTr: "Yeni kelimeleri not defterine yaz." },
  { word: "oven", meaning: "fırın", sentenceEn: "The delicious cake is baking in the oven.", sentenceTr: "Lezzetli kek fırında pişiyor." },
  { word: "pillow", meaning: "yastık", sentenceEn: "A soft pillow helps you sleep comfortably.", sentenceTr: "Yumuşak bir yastık rahat uyumanıza yardımcı olur." },
  { word: "plate", meaning: "tabak", sentenceEn: "He placed a fresh slice of pizza on the plate.", sentenceTr: "Tabağa taze bir dilim pizza koydu." },
  { word: "refrigerator", meaning: "buzdolabı", sentenceEn: "Store fresh milk inside the refrigerator.", sentenceTr: "Taze sütü buzdolabında saklayın." },
  { word: "ring", meaning: "yüzük", sentenceEn: "He gave her a gold ring on their anniversary.", sentenceTr: "Yıldönümlerinde ona altın bir yüzük hediye etti." },
  { word: "rope", meaning: "ip, halat", sentenceEn: "Tie the boat securely with a strong rope.", sentenceTr: "Tekneyi sağlam bir halatla güvenli bir şekilde bağlayın." },
  { word: "scissors", meaning: "makas", sentenceEn: "Use scissors to cut along the dotted line.", sentenceTr: "Noktalı çizgi boyunca kesmek için makas kullanın." },
  { word: "shelf", meaning: "raf", sentenceEn: "He placed the heavy encyclopedia on the top shelf.", sentenceTr: "Ağır ansiklopediyi en üstteki rafa yerleştirdi." },
  { word: "shirt", meaning: "gömlek", sentenceEn: "He wore a crisp white shirt for the meeting.", sentenceTr: "Toplantı için temiz beyaz bir gömlek giydi." },
  { word: "shoes", meaning: "ayakkabı", sentenceEn: "Take off your shoes before entering the house.", sentenceTr: "Eve girmeden önce ayakkabılarınızı çıkarın." },
  { word: "soap", meaning: "sabun", sentenceEn: "Wash your hands with warm water and soap.", sentenceTr: "Ellerinizi ılık su ve sabunla yıkayın." },
  { word: "spoon", meaning: "kaşık", sentenceEn: "She stirred her hot soup with a silver spoon.", sentenceTr: "Sıcak çorbasını gümüş bir kaşıkla karıştırdı." },
  { word: "suitcase", meaning: "valiz, bavul", sentenceEn: "Pack your suitcase tonight for tomorrow's flight.", sentenceTr: "Yarınki uçuş için bu gece valizini hazırla." },
  { word: "table", meaning: "masa", sentenceEn: "We all gathered around the dinner table.", sentenceTr: "Hepimiz akşam yemeği masasının etrafında toplandık." },
  { word: "telephone", meaning: "telefon", sentenceEn: "The telephone rang loudly in the empty room.", sentenceTr: "Boş odada telefon yüksek sesle çaldı." },
  { word: "ticket", meaning: "bilet", sentenceEn: "Show your boarding ticket to the flight attendant.", sentenceTr: "Uçuş görevlisine biniş biletinizi gösterin." },
  { word: "toothbrush", meaning: "diş fırçası", sentenceEn: "Dentists recommend replacing your toothbrush every three months.", sentenceTr: "Diş hekimleri diş fırçanızı her üç ayda bir değiştirmenizi önerir." },
  { word: "towel", meaning: "havlu", sentenceEn: "Dry your wet hands with a clean towel.", sentenceTr: "Islak ellerinizi temiz bir havluyla kurulayın." },
  { word: "umbrella", meaning: "şemsiye", sentenceEn: "Take an umbrella because it might rain today.", sentenceTr: "Bugün yağmur yağabilir, yanına bir şemsiye al." },
  { word: "vase", meaning: "vazo", sentenceEn: "She placed fresh roses into the glass vase.", sentenceTr: "Cam vazoya taze güller yerleştirdi." },
  { word: "wallet", meaning: "cüzdan", sentenceEn: "He realized he left his wallet at the supermarket.", sentenceTr: "Cüzdanını süpermarkette unuttuğunu fark etti." },
  { word: "watch", meaning: "kol saati", sentenceEn: "My grandfather gave me this vintage watch.", sentenceTr: "Büyükbabam bana bu klasik kol saatini verdi." },
  { word: "wheel", meaning: "tekerlek, direksiyon", sentenceEn: "The mechanic changed the flat wheel quickly.", sentenceTr: "Tamirci patlak tekerleği hızlıca değiştirdi." },
  { word: "window", meaning: "pencere", sentenceEn: "Open the window to let some fresh air inside.", sentenceTr: "İçeriye biraz temiz hava girmesi için pencereyi aç." },
  { word: "wrench", meaning: "somun anahtarı, ingiliz anahtarı", sentenceEn: "He tightened the loose pipe with a wrench.", sentenceTr: "Gevşek boruyu somun anahtarıyla sıktı." }
];

// 50 Adverbs
const adverbs = [
  { word: "accidentally", meaning: "kazara, yanlışlıkla", sentenceEn: "I accidentally deleted the important document.", sentenceTr: "Önemli belgeyi kazara sildim." },
  { word: "actually", meaning: "aslında, doğrusu", sentenceEn: "I thought it was hard, but it is actually quite simple.", sentenceTr: "Zor olduğunu düşünmüştüm ama aslında oldukça basit." },
  { word: "almost", meaning: "neredeyse, hemen hemen", sentenceEn: "We are almost ready to begin the presentation.", sentenceTr: "Sunuma başlamak için neredeyse hazırız." },
  { word: "already", meaning: "zaten, çoktan", sentenceEn: "I have already finished today's homework.", sentenceTr: "Bugünkü ödevimi çoktan bitirdim." },
  { word: "always", meaning: "her zaman, daima", sentenceEn: "She always drinks water right after waking up.", sentenceTr: "Uyandıktan hemen sonra daima su içer." },
  { word: "barely", meaning: "zar zor, güçlükle", sentenceEn: "He could barely hear what the speaker said.", sentenceTr: "Konuşmacının ne söylediğini zar zor duyabildi." },
  { word: "briefly", meaning: "kısaca", sentenceEn: "Let me briefly explain the agenda of our meeting.", sentenceTr: "Toplantımızın gündemini kısaca açıklamama izin verin." },
  { word: "calmly", meaning: "sakince, sükunetle", sentenceEn: "He answered all difficult questions calmly.", sentenceTr: "Tüm zor soruları sakince yanıtladı." },
  { word: "carefully", meaning: "dikkatlice, özenle", sentenceEn: "Read the contract carefully before signing it.", sentenceTr: "İmzalamadan önce sözleşmeyi dikkatlice okuyun." },
  { word: "certainly", meaning: "kesinlikle, şüphesiz", sentenceEn: "I will certainly attend your birthday celebration.", sentenceTr: "Doğum günü kutlamana kesinlikle katılacağım." },
  { word: "clearly", meaning: "açıkça, net bir şekilde", sentenceEn: "The teacher explained the topic clearly.", sentenceTr: "Öğretmen konuyu net bir şekilde açıkladı." },
  { word: "completely", meaning: "tamamen, bütünüyle", sentenceEn: "The puzzle is now completely solved.", sentenceTr: "Bulmaca artık tamamen çözüldü." },
  { word: "constantly", meaning: "sürekli, durmaksızın", sentenceEn: "Technology is constantly evolving every year.", sentenceTr: "Teknoloji her yıl sürekli gelişiyor." },
  { word: "definitely", meaning: "kesinlikle, mutlaka", sentenceEn: "You should definitely watch this documentary.", sentenceTr: "Bu belgeseli kesinlikle izlemelisin." },
  { word: "deliberately", meaning: "kasten, bilerek", sentenceEn: "He did not deliberately break your favorite cup.", sentenceTr: "En sevdiğin fincanı kasten kırmadı." },
  { word: "easily", meaning: "kolayca, rahatlıkla", sentenceEn: "You can easily learn English with consistent practice.", sentenceTr: "Düzenli pratikle kolayca İngilizce öğrenebilirsiniz." },
  { word: "especially", meaning: "özellikle, bilhassa", sentenceEn: "I love Italian food, especially homemade pasta.", sentenceTr: "İtalyan yemeklerini severim, özellikle ev yapımı makarnayı." },
  { word: "eventually", meaning: "eninde sonunda, nihayetinde", sentenceEn: "Hard work will eventually pay off.", sentenceTr: "Sıkı çalışma eninde sonunda karşılığını verecektir." },
  { word: "exactly", meaning: "tam olarak, aynen", sentenceEn: "That is exactly what I was trying to say.", sentenceTr: "Benim de tam olarak söylemeye çalıştığım buydu." },
  { word: "finally", meaning: "sonunda, nihayet", sentenceEn: "After five hours of driving, we finally reached the hotel.", sentenceTr: "Beş saatlik araba yolculuğunun ardından nihayet otele ulaştık." },
  { word: "frequently", meaning: "sık sık, çoğunlukla", sentenceEn: "Students frequently visit the university library.", sentenceTr: "Öğrenciler üniversite kütüphanesini sık sık ziyaret eder." },
  { word: "generally", meaning: "genellikle, genel olarak", sentenceEn: "Prices are generally higher in large capital cities.", sentenceTr: "Büyük başkentlerde fiyatlar genellikle daha yüksektir." },
  { word: "gradually", meaning: "kademeli olarak, yavaş yavaş", sentenceEn: "Her English pronunciation is gradually improving.", sentenceTr: "İngilizce telaffuzu yavaş yavaş gelişiyor." },
  { word: "hardly", meaning: "neredeyse hiç", sentenceEn: "There was hardly anyone at the station early in the morning.", sentenceTr: "Sabahın erken saatlerinde istasyonda neredeyse hiç kimse yoktu." },
  { word: "immediately", meaning: "derhal, hemen", sentenceEn: "Call an ambulance immediately if someone is hurt.", sentenceTr: "Biri yaralandıysa derhal ambulans çağırın." },
  { word: "initially", meaning: "başlangıçta, ilk olarak", sentenceEn: "Initially, I found programming very challenging.", sentenceTr: "Başlangıçta programlamayı çok zor bulmuştum." },
  { word: "mostly", meaning: "çoğunlukla, ağırlıklı olarak", sentenceEn: "The audience was mostly university students.", sentenceTr: "Seyirciler çoğunlukla üniversite öğrencileriydi." },
  { word: "naturally", meaning: "doğal olarak", sentenceEn: "Naturally, we were curious to hear the big announcement.", sentenceTr: "Doğal olarak büyük duyuruyu duymak için meraklandık." },
  { word: "nearly", meaning: "neredeyse, yaklaşık olarak", sentenceEn: "It took nearly three weeks to complete the website.", sentenceTr: "Web sitesini tamamlamak yaklaşık üç hafta sürdü." },
  { word: "necessarily", meaning: "mutlaka, illa ki", sentenceEn: "Expensive things are not necessarily higher quality.", sentenceTr: "Pahalı şeyler illa ki daha kaliteli olmak zorunda değildir." },
  { word: "never", meaning: "asla, hiçbir zaman", sentenceEn: "Never give up on your dreams.", sentenceTr: "Hayallerinden asla vazgeçme." },
  { word: "normally", meaning: "normalde, olağan şartlarda", sentenceEn: "I normally wake up at seven o'clock.", sentenceTr: "Normalde saat yedide uyanırım." },
  { word: "obviously", meaning: "besbelli, açıkça", sentenceEn: "She was obviously thrilled with the surprise gift.", sentenceTr: "Sürpriz hediye karşısında besbelli çok heyecanlanmıştı." },
  { word: "occasionally", meaning: "ara sıra, bazen", sentenceEn: "We occasionally go camping in the mountains.", sentenceTr: "Dağlarda ara sıra kampa gideriz." },
  { word: "often", meaning: "sık sık", sentenceEn: "How often do you read books in English?", sentenceTr: "Ne sıklıkla İngilizce kitap okursunuz?" },
  { word: "perfectly", meaning: "kusursuzca, mükemmel şekilde", sentenceEn: "The new suit fits him perfectly.", sentenceTr: "Yeni takım elbise onun üzerine kusursuzca oturdu." },
  { word: "probably", meaning: "muhtemelen", sentenceEn: "It will probably snow tomorrow morning.", sentenceTr: "Yarın sabah muhtemelen kar yağacak." },
  { word: "quickly", meaning: "hızlıca, çabucak", sentenceEn: "Finish your breakfast quickly so we won't be late.", sentenceTr: "Geç kalmamamız için kahvaltını çabucak bitir." },
  { word: "quietly", meaning: "sessizce", sentenceEn: "Please close the door quietly because the baby is sleeping.", sentenceTr: "Lütfen kapıyı sessizce kapatın çünkü bebek uyuyor." },
  { word: "rarely", meaning: "nadiren", sentenceEn: "He rarely eats fast food because he cares about health.", sentenceTr: "Sağlığına önem verdiği için nadiren hazır yemek yer." },
  { word: "really", meaning: "gerçekten", sentenceEn: "I really appreciate your help with this project.", sentenceTr: "Bu projedeki yardımınızı gerçekten takdir ediyorum." },
  { word: "recently", meaning: "son zamanlarda, geçenlerde", sentenceEn: "Have you watched any good movies recently?", sentenceTr: "Son zamanlarda hiç güzel bir film izledin mi?" },
  { word: "regularly", meaning: "düzenli olarak", sentenceEn: "You should exercise regularly to stay fit.", sentenceTr: "Formda kalmak için düzenli olarak egzersiz yapmalısınız." },
  { word: "seldom", meaning: "nadiren, pek az", sentenceEn: "He seldom complains about difficult working conditions.", sentenceTr: "Zorlu çalışma koşullarından nadiren şikayet eder." },
  { word: "simply", meaning: "basitçe, sadece", sentenceEn: "It is simply the best coffee shop in our town.", sentenceTr: "Burası kasabamızdaki açık ara en iyi kahve dükkanı." },
  { word: "slowly", meaning: "yavaşça", sentenceEn: "Speak more slowly so the beginner can understand.", sentenceTr: "Yeni başlayanın anlayabilmesi için daha yavaş konuşun." },
  { word: "sometimes", meaning: "bazen, kimi zaman", sentenceEn: "Sometimes taking a short break solves the problem.", sentenceTr: "Bazen kısa bir mola vermek sorunu çözer." },
  { word: "suddenly", meaning: "aniden, birdenbire", sentenceEn: "Suddenly, the electricity went out during the storm.", sentenceTr: "Fırtına sırasında elektrik birdenbire kesildi." },
  { word: "totally", meaning: "tamamen, bütünüyle", sentenceEn: "I totally agree with what you just explained.", sentenceTr: "Az önce açıkladığınız şeye tamamen katılıyorum." },
  { word: "usually", meaning: "genellikle, çoğunlukla", sentenceEn: "He usually takes the subway to get to work.", sentenceTr: "İşe gitmek için genellikle metroyu kullanır." }
];

// 50 Sentence Patterns / Phrases
const idioms = [
  { word: "How are you doing?", meaning: "Nasıl gidiyor? / Nasılsın?", sentenceEn: "Hi Sarah, how are you doing today?", sentenceTr: "Selam Sarah, bugün nasıl gidiyor?" },
  { word: "Nice to meet you", meaning: "Tanıştığıma memnun oldum", sentenceEn: "Welcome to the team, nice to meet you!", sentenceTr: "Ekibe hoş geldin, tanıştığıma memnun oldum!" },
  { word: "Long time no see", meaning: "Görüşmeyeli uzun zaman oldu", sentenceEn: "Long time no see, what have you been up to?", sentenceTr: "Görüşmeyeli uzun zaman oldu, neler yapıyorsun?" },
  { word: "What's going on?", meaning: "Neler oluyor? / Ne var ne yok?", sentenceEn: "Hey guys, what's going on here?", sentenceTr: "Hey millet, burada neler oluyor?" },
  { word: "Could you help me?", meaning: "Bana yardım edebilir misiniz?", sentenceEn: "Excuse me, could you help me carry this box?", sentenceTr: "Afedersiniz, bu kutuyu taşımama yardım edebilir misiniz?" },
  { word: "I would like to", meaning: "... yapmak isterim / rica ediyorum", sentenceEn: "I would like to order a cup of black coffee.", sentenceTr: "Bir fincan sade kahve sipariş etmek isterim." },
  { word: "It doesn't matter", meaning: "Fark etmez / Önemli değil", sentenceEn: "We can leave now or later, it doesn't matter.", sentenceTr: "Şimdi veya sonra çıkabiliriz, hiç fark etmez." },
  { word: "Never mind", meaning: "Boşver / Zararı yok", sentenceEn: "I found my keys already, so never mind!", sentenceTr: "Anahtarlarımı zaten buldum, bu yüzden boşver!" },
  { word: "As soon as possible", meaning: "Mümkün olan en kısa sürede (ASAP)", sentenceEn: "Please send me the final report as soon as possible.", sentenceTr: "Lütfen nihai raporu bana mümkün olan en kısa sürede gönderin." },
  { word: "Take care of yourself", meaning: "Kendine iyi bak", sentenceEn: "Have a safe flight and take care of yourself.", sentenceTr: "İyi uçuşlar ve kendine çok iyi bak." },
  { word: "I'm looking forward to", meaning: "... dört gözle bekliyorum", sentenceEn: "I'm looking forward to meeting your family this weekend.", sentenceTr: "Bu hafta sonu ailenle tanışmayı dört gözle bekliyorum." },
  { word: "By the way", meaning: "Bu arada / Sırası gelmişken", sentenceEn: "By the way, did you receive the invitation email?", sentenceTr: "Bu arada, davet e-postasını aldın mı?" },
  { word: "To be honest", meaning: "Dürüst olmak gerekirse", sentenceEn: "To be honest, I did not really enjoy that movie.", sentenceTr: "Dürüst olmak gerekirse, o filmden pek keyif almadım." },
  { word: "In my opinion", meaning: "Bana göre / Benim fikrime göre", sentenceEn: "In my opinion, consistency is the key to success.", sentenceTr: "Bana göre başarının anahtarı istikrardır." },
  { word: "I have no idea", meaning: "Hiçbir fikrim yok", sentenceEn: "I have no idea where the nearest pharmacy is located.", sentenceTr: "En yakın eczanenin nerede olduğuna dair hiçbir fikrim yok." },
  { word: "Make yourself at home", meaning: "Kendini evinde gibi hisset", sentenceEn: "Please come in and make yourself at home.", sentenceTr: "Lütfen içeri gelin ve kendinizi evinizde gibi hissedin." },
  { word: "It's up to you", meaning: "Sana bağlı / Sen bilirsin", sentenceEn: "We can eat pizza or sushi, it's up to you.", sentenceTr: "Pizza da yiyebiliriz suşi de, sen bilirsin." },
  { word: "Keep in touch", meaning: "İrtibatta kalalım / Bağlantıyı koparma", sentenceEn: "It was great seeing you, let's keep in touch!", sentenceTr: "Seni görmek harikaydı, irtibatta kalalım!" },
  { word: "Don't get me wrong", meaning: "Beni yanlış anlama", sentenceEn: "Don't get me wrong, I like the car, but it is too expensive.", sentenceTr: "Beni yanlış anlama, arabayı beğendim ama çok pahalı." },
  { word: "Are you kidding me?", meaning: "Benimle dalga mı geçiyorsun? / Şaka mı yapıyorsun?", sentenceEn: "You won the lottery? Are you kidding me?", sentenceTr: "Piyangoyu mu kazandın? Benimle dalga mı geçiyorsun?" },
  { word: "I couldn't agree more", meaning: "Sana kesinlikle sonuna kadar katılıyorum", sentenceEn: "Your analysis is spot on, I couldn't agree more.", sentenceTr: "Analizin tam isabet, sana kesinlikle katılıyorum." },
  { word: "That makes sense", meaning: "Bu mantıklı geliyor / Akla yatkın", sentenceEn: "Thank you for explaining, that makes a lot of sense.", sentenceTr: "Açıkladığın için teşekkürler, bu oldukça mantıklı geliyor." },
  { word: "No hard feelings", meaning: "Alınmaca gücenmece yok", sentenceEn: "It was just a friendly game, no hard feelings.", sentenceTr: "Sadece dostça bir oyundu, kırılmaca yok." },
  { word: "Take your time", meaning: "Acele etme / Vaktini al", sentenceEn: "Take your time, we still have thirty minutes before the train leaves.", sentenceTr: "Acele etme, tren kalkmadan önce hala otuz dakikamız var." },
  { word: "So far so good", meaning: "Şimdilik her şey yolunda", sentenceEn: "How is your new job? So far so good!", sentenceTr: "Yeni işin nasıl gidiyor? Şimdilik her şey yolunda!" },
  { word: "Better late than never", meaning: "Geç olsun da güç olmasın", sentenceEn: "You finally joined our gym, better late than never.", sentenceTr: "Sonunda spor salonumuza katıldın, geç olsun da güç olmasın." },
  { word: "Break a leg", meaning: "Şansın bol olsun / Başarılar (sahne/sınav öncesi)", sentenceEn: "You have rehearsed all week, now go out there and break a leg!", sentenceTr: "Bütün hafta prova yaptın, şimdi oraya çık ve bol şans!" },
  { word: "Call it a day", meaning: "Bugünlük bu kadar yeter demek / İşi noktalamak", sentenceEn: "We worked for ten hours straight, let's call it a day.", sentenceTr: "Aralıksız on saat çalıştık, bugünlük bu kadar yeter diyelim." },
  { word: "Get out of hand", meaning: "Çığırından çıkmak / Kontrolden çıkmak", sentenceEn: "The argument got out of hand quickly.", sentenceTr: "Tartışma hızlı bir şekilde kontrolden çıktı." },
  { word: "Hang in there", meaning: "Dayan / Sabret / Pes etme", sentenceEn: "Exam week is tough, but hang in there!", sentenceTr: "Sınav haftası zordur ama dayan, pes etme!" },
  { word: "Hit the nail on the head", meaning: "Tam üstüne basmak / Tam hedeften vurmak", sentenceEn: "Her comment hit the nail on the head.", sentenceTr: "Onun yorumu konunun tam üstüne bastı." },
  { word: "Under the weather", meaning: "Keyifsiz / Halsiz / Hafif hasta", sentenceEn: "I will stay home today because I feel a bit under the weather.", sentenceTr: "Bugün kendimi biraz halsiz hissettiğim için evde kalacağım." },
  { word: "A piece of cake", meaning: "Çantada keklik / Çocuk oyuncağı", sentenceEn: "Don't worry about the quiz, it will be a piece of cake.", sentenceTr: "Küçük sınav için endişelenme, çocuk oyuncağı olacak." },
  { word: "Once in a blue moon", meaning: "Kırk yılda bir / Ayda yılda bir", sentenceEn: "He only goes to the theater once in a blue moon.", sentenceTr: "Tiyatroya sadece kırk yılda bir gider." },
  { word: "See eye to eye", meaning: "Aynı fikirde olmak / Uyuşmak", sentenceEn: "My brother and I rarely see eye to eye on politics.", sentenceTr: "Kardeşim ve ben politika konusunda nadiren aynı fikirde oluruz." },
  { word: "Cost an arm and a leg", meaning: "Ateş pahası olmak / Çok pahalıya patlamak", sentenceEn: "Buying that designer bag cost an arm and a leg.", sentenceTr: "O marka çantayı satın almak bir servete patladı." },
  { word: "Let the cat out of the bag", meaning: "Ağzından baklayı çıkarmak / Sırrı ifşa etmek", sentenceEn: "It was supposed to be a surprise party, but Tim let the cat out of the bag.", sentenceTr: "Sürpriz bir parti olacaktı ama Tim ağzından baklayı çıkardı." },
  { word: "Burn the midnight oil", meaning: "Geceleri sabahlamak / Çok sıkı ders çalışmak", sentenceEn: "She burned the midnight oil to prepare for her medical exam.", sentenceTr: "Tıp sınavına hazırlanmak için gecesini gündüzüne kattı." },
  { word: "Cut to the chase", meaning: "Sadede gelmek / Lafı dolandırmamak", sentenceEn: "We don't have much time, so please cut to the chase.", sentenceTr: "Fazla zamanımız yok, bu yüzden lütfen sadede gelin." },
  { word: "Bite off more than you can chew", meaning: "Boyundan büyük işe kalkışmak", sentenceEn: "Taking four projects at once was biting off more than he could chew.", sentenceTr: "Aynı anda dört proje almak boyundan büyük bir işe kalkışmaktı." },
  { word: "Back to square one", meaning: "En başa dönmek / Sıfırdan başlamak", sentenceEn: "The software crashed and we are back to square one.", sentenceTr: "Yazılım çöktü ve yine en başa döndük." },
  { word: "On cloud nine", meaning: "Havalara uçmak / Etekleri zil çalmak", sentenceEn: "He was on cloud nine when he received the scholarship.", sentenceTr: "Bursu kazandığında sevinçten havalara uçtu." },
  { word: "Cross that bridge when we come to it", meaning: "O gün gelince düşünmek / Zamanı gelince bakmak", sentenceEn: "Let's not worry about the future, we will cross that bridge when we come to it.", sentenceTr: "Gelecek için endişelenmeyelim, o gün gelince düşünürüz." },
  { word: "Leave no stone unturned", meaning: "Her yolu denemek / Her taşın altına bakmak", sentenceEn: "The police left no stone unturned to find the missing child.", sentenceTr: "Polis kayıp çocuğu bulmak için her yolu denedi." },
  { word: "Pull someone's leg", meaning: "Biriyle şaka yollu kafa bulmak", sentenceEn: "Relax, I am just pulling your leg!", sentenceTr: "Sakin ol, sadece seninle kafa buluyorum!" },
  { word: "The best of both worlds", meaning: "Bir taşla iki kuş / İki dünyanın da avantajı", sentenceEn: "Working from home offers the best of both worlds.", sentenceTr: "Evden çalışmak her iki dünyanın da en iyi yönlerini sunuyor." },
  { word: "Through thick and thin", meaning: "İyi günde kötü günde / Her koşulda", sentenceEn: "True friends stay together through thick and thin.", sentenceTr: "Gerçek dostlar iyi günde kötü günde hep bir arada kalırlar." },
  { word: "You can say that again", meaning: "Kesinlikle çok haklısın / Ağzına sağlık", sentenceEn: "This weather is freezing! You can say that again!", sentenceTr: "Hava buz gibi! Kesinlikle çok haklısın!" },
  { word: "Time flies", meaning: "Zaman su gibi akıp geçiyor", sentenceEn: "Time flies when you are having fun with good friends.", sentenceTr: "İyi arkadaşlarla eğlenirken zaman su gibi akıp geçiyor." },
  { word: "Speak of the devil", meaning: "Lafın üstüne gelmek / İti an çomağı hazırla", sentenceEn: "Speak of the devil! We were just talking about you, Mark.", sentenceTr: "Lafın üstüne geldin! Biz de tam senden bahsediyorduk Mark." }
];

function compileAll() {
  const allItems = [];
  let idCounter = 1;

  function addGroup(items, pos) {
    items.forEach(item => {
      allItems.push({
        id: `word-${idCounter++}`,
        word: item.word,
        meaning: item.meaning,
        partOfSpeech: pos,
        sentenceEn: item.sentenceEn,
        sentenceTr: item.sentenceTr,
        box: 1,
        lastReviewed: null,
        successCount: 0,
        failCount: 0,
        createdAt: new Date().toISOString()
      });
    });
  }

  addGroup(verbs, 'verb');
  addGroup(adjectives, 'adjective');
  addGroup(nouns, 'noun');
  addGroup(adverbs, 'adverb');
  addGroup(idioms, 'idiom');

  fs.writeFileSync(DATA_FILE, JSON.stringify(allItems, null, 2), 'utf8');
  console.log(`Successfully generated and seeded ${allItems.length} items to words.json!`);
  console.log(`Verbs: ${verbs.length}, Adjectives: ${adjectives.length}, Nouns: ${nouns.length}, Adverbs: ${adverbs.length}, Phrases: ${idioms.length}`);
}

compileAll();
